const CONFIG = {
  SPREADSHEET_ID: "PASTE_GOOGLE_SHEET_ID_HERE",
  DRIVE_FOLDER_ID: "PASTE_GOOGLE_DRIVE_RSVP_FOLDER_ID_HERE",
  NOTIFICATION_EMAIL: "prsvas@gmail.com",
  WEDDING_NAME: "Anisha & Srivatsan",
  WEDDING_DATE: "25 October 2026",
  WEDDING_VENUE: "Haryana Bhavan, Secunderabad"
};
const SHEET_NAME = "RSVP Database";
const DASHBOARD_NAME = "Dashboard";
const HEADERS = ["Timestamp","Guest / Family Name","Mobile Number","Attendance","Adults","Kids","Total Guests","Kids Under 5","Kids 5–12","Kids 13+","Accommodation","Special Note","RSVP Source"];
function doGet(){return json_({success:true,message:"Anisha & Srivatsan RSVP API is running."});}
function doPost(e){try{if(!e?.postData?.contents)throw new Error("No RSVP data received.");const d=JSON.parse(e.postData.contents);validate_(d);const lock=LockService.getScriptLock();lock.waitLock(10000);try{const ss=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);const sh=getSheet_(ss,SHEET_NAME);setup_(sh);const yes=d.attendance==="Yes";const adults=yes?Number(d.adults||0):0;const kids=yes?Number(d.kids||0):0;const row=[new Date(),clean_(d.name),clean_(d.mobile),yes?"Yes":"No",adults,kids,adults+kids,Number(d.kidsUnder5||0),Number(d.kids5to12||0),Number(d.kids13Plus||0),yes?clean_(d.accommodation||"No"):"No",clean_(d.note||""),"Wedding Website"];const dup=findDuplicate_(sh,d.name,d.mobile);if(dup)sh.getRange(dup,1,1,row.length).setValues([row]);else sh.appendRow(row);const summary=summary_(sh);dashboard_(ss,summary);email_(d,summary,adults+kids);drive_(summary);return json_({success:true,message:yes?"Your RSVP has been received. We look forward to celebrating with you!":"Thank you for letting us know. We hope to celebrate together another time.",data:{totalGuests:adults+kids}});}finally{lock.releaseLock();}}catch(err){return json_({success:false,message:String(err.message||err)});}}
function validate_(d){if(!d.name||String(d.name).trim().length<2)throw new Error("Name is required.");if(!d.mobile||String(d.mobile).trim().length<5)throw new Error("Mobile number is required.");if(!["Yes","No"].includes(d.attendance))throw new Error("Invalid attendance value.");if(d.attendance==="Yes"){const a=Number(d.adults),k=Number(d.kids);if(!Number.isInteger(a)||a<1||a>10)throw new Error("Adults must be between 1 and 10.");if(!Number.isInteger(k)||k<0||k>10)throw new Error("Kids must be between 0 and 10.");}}
function getSheet_(ss,n){return ss.getSheetByName(n)||ss.insertSheet(n);}
function setup_(sh){if(sh.getLastRow()===0)sh.appendRow(HEADERS);sh.setFrozenRows(1);sh.getRange(1,1,1,HEADERS.length).setFontWeight("bold");}
function findDuplicate_(sh,name,mobile){const n=sh.getLastRow();if(n<2)return null;const rows=sh.getRange(2,1,n-1,HEADERS.length).getValues();const nm=clean_(name).toLowerCase(),ph=String(mobile).replace(/\D/g,"");for(let i=0;i<rows.length;i++){if(String(rows[i][1]||"").trim().toLowerCase()===nm&&String(rows[i][2]||"").replace(/\D/g,"")===ph)return i+2;}return null;}
function summary_(sh){const s={responses:0,confirmedFamilies:0,notAttending:0,adults:0,kids:0,totalGuests:0,accommodation:0};const n=sh.getLastRow();if(n<2)return s;const rows=sh.getRange(2,1,n-1,HEADERS.length).getValues();s.responses=rows.length;rows.forEach(r=>{if(String(r[3])==="Yes"){s.confirmedFamilies++;s.adults+=Number(r[4]||0);s.kids+=Number(r[5]||0);s.totalGuests+=Number(r[6]||0);if(String(r[10])==="Yes")s.accommodation++;}else if(String(r[3])==="No")s.notAttending++;});return s;}
function dashboard_(ss,s){let sh=ss.getSheetByName(DASHBOARD_NAME)||ss.insertSheet(DASHBOARD_NAME);sh.clear();sh.getRange("A1:B1").merge().setValue(CONFIG.WEDDING_NAME+" — RSVP DASHBOARD").setFontSize(18).setFontWeight("bold");sh.getRange("A3:B10").setValues([["Metric","Count"],["Total Responses",s.responses],["Confirmed Families",s.confirmedFamilies],["Not Attending",s.notAttending],["Total Adults",s.adults],["Total Kids",s.kids],["TOTAL GUESTS",s.totalGuests],["Accommodation Required",s.accommodation]]);sh.getRange("A3:B3").setFontWeight("bold");sh.autoResizeColumns(1,2);}
function email_(d,s,total){const yes=d.attendance==="Yes";const subject=yes?`New Wedding RSVP — ${d.name} | ${total} Guest${total===1?"":"s"}`:`Wedding RSVP — Unable to Attend | ${d.name}`;const body=["ANISHA & SRIVATSAN — WEDDING RSVP","",`Guest / Family: ${d.name}`,`Mobile: ${d.mobile}`,`Attendance: ${d.attendance}`,`Adults: ${yes?d.adults:0}`,`Kids: ${yes?d.kids:0}`,`Total Guests: ${total}`,`Accommodation: ${yes?(d.accommodation||"No"):"No"}`,`Special Note: ${d.note||"—"}`,"","CURRENT RSVP SUMMARY",`Confirmed Families: ${s.confirmedFamilies}`,`Not Attending: ${s.notAttending}`,`Adults: ${s.adults}`,`Kids: ${s.kids}`,`TOTAL GUESTS: ${s.totalGuests}`,`Accommodation Required: ${s.accommodation}`].join("\n");GmailApp.sendEmail(CONFIG.NOTIFICATION_EMAIL,subject,body);}
function drive_(s){if(!CONFIG.DRIVE_FOLDER_ID||CONFIG.DRIVE_FOLDER_ID.includes("PASTE_"))return;const folder=DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID),name="Anisha & Srivatsan — RSVP Summary.txt",content=["ANISHA & SRIVATSAN — RSVP SUMMARY","",`Wedding Date: ${CONFIG.WEDDING_DATE}`,`Venue: ${CONFIG.WEDDING_VENUE}`,`Generated: ${new Date()}`,"",`Total Responses: ${s.responses}`,`Confirmed Families: ${s.confirmedFamilies}`,`Not Attending: ${s.notAttending}`,`Adults: ${s.adults}`,`Kids: ${s.kids}`,`TOTAL GUESTS: ${s.totalGuests}`,`Accommodation Required: ${s.accommodation}`].join("\n");const f=folder.getFilesByName(name);if(f.hasNext())f.next().setContent(content);else folder.createFile(name,content);}
function clean_(v){return String(v??"").replace(/[<>]/g,"").trim();}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
